name: CI pipeline
on: #kon jayagy pipeline er operation perform korbo set indicate kore 
  push: #push command dewar sathe sathe main name er branch er modde operation hobe
    branches: [ main ]
jobs: #ki ki operation run hobe seta define kore 
  build:
    runs-on: ubuntu-latest # eita te run korar  reason holo.. lightweight and fast
  steps: #step er name and kon step e ki ki action hobe seta define kore 
    - name: checkout code
      uses: actions/checkout@v4 #checkout@v4 holo predefined action
    - name: set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test   
           